django_files/urls.py
"""

Acest fișier reprezintă configurarea URL-urilor (rutele) pentru aplicația ta Django și este 
esențial pentru a direcționa cererile HTTP către view-urile corespunzătoare ale aplicației tale.

"""

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


"""

urlpatterns: Această listă conține toate rutele URL ale aplicației tale Django și indică către 
care view-uri trebuie să fie direcționate cererile HTTP. În exemplul tău, există două rute definite:

path('admin/', admin.site.urls): Această rută direcționează toate cererile care încep cu '/admin/' 
către panoul de administrare Django. Acesta este locul în care poți gestiona datele și configurările 
aplicației tale.

path('', include('main.urls', namespace="main")): Această rută direcționează cererile care nu se potrivesc
cu nicio altă rută către aplicația principală, care este definită în alt modul numit 'main.urls'. De asemenea,
un spațiu de nume (namespace) "main" este atribuit acestei aplicații, ceea ce permite gestionarea mai ușoară
a rutelor din aceasta.

"""

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
]

"""

Blocul if settings.DEBUG: Acest bloc de cod verifică dacă setarea DEBUG din fișierul de configurare 
Django (settings.py) este setată pe True. Dacă acesta este cazul, atunci se adaugă rute suplimentare 
pentru servirea fișierelor statice și a fișierelor media în timpul dezvoltării. Acest lucru este util 
pentru a putea vedea imediat schimbările în fișierele statice și media în timp ce dezvolți.


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT): Această linie adaugă o 
rută pentru servirea fișierelor statice (de exemplu, fișierele CSS și JavaScript) din directorul specificat 
în setările (STATIC_ROOT) la URL-ul specificat (STATIC_URL).


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT): Această linie adaugă o rută 
pentru servirea fișierelor media (de exemplu, imagini încărcate de utilizatori) din directorul specificat 
în setările (MEDIA_ROOT) la URL-ul specificat (MEDIA_URL).

"""

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


"""

Acest fișier de configurare pentru URL-uri asigură că cererile HTTP sunt corect direcționate 
către view-urile corespunzătoare în aplicația ta Django, facilitând astfel funcționarea 
corectă a site-ului web.

"""

main/urls.py
"""

Acest fragment de cod reprezintă definirea rutelor URL (Uniform Resource Locator)pentru 
aplicația web Django. Rutele URL sunt utilizate pentru a determina cum sunt mapate adresele URL 
ale cererilor primite de la utilizatori la funcțiile și metodele corespunzătoare din aplicație. 
În acest caz, fragmentul de cod definește următoarele lucruri:

"""
# from django.urls import path: Se importă modulul path din Django, care este folosit pentru a defini rute URL pentru aplicație.

from django.urls import path
from . import views

"""

app_name = "main": Se definește un nume de aplicație pentru a evita conflicte de nume 
între diferite aplicații Django. Acest nume de aplicație este utilizat pentru a grupa 
rutele URL specifice acelei aplicații.

"""

app_name = "main"

"""

urlpatterns: Aici este definită o listă de rute URL și funcțiile corespunzătoare pe care 
trebuie să le fie asociate. Fiecare rută URL este definită folosind funcția path.

"""

urlpatterns = [
	path('', views.IndexView.as_view(), name="home"),
	path('contact/', views.ContactView.as_view(), name="contact"),
	path('portfolio/', views.PortfolioView.as_view(), name="portfolios"),
	path('portfolio/<slug:slug>', views.PortfolioDetailView.as_view(), name="portfolio"),
	path('blog/', views.BlogView.as_view(), name="blogs"),
	path('blog/<slug:slug>', views.BlogDetailView.as_view(), name="blog"),
	]

"""

Aceste rute URL și vizualizările asociate permit navigarea și afișarea diferitelor pagini 
și conținut în cadrul aplicației web Django. Prin definirea acestor rute, poți gestiona modul
în care cererile utilizatorilor sunt procesate și afișate în aplicație.

"""

main/forms.py
"""

Acest fragment de cod este o clasă definită în Django care reprezintă un formular web utilizat 
pentru a colecta și valida datele introduse de utilizatori. Formularul este legat de modelul Django 
ContactProfile, ceea ce înseamnă că datele introduse de utilizator în acest formular vor fi validate 
și salvate în baza de date utilizând modelul ContactProfile.

"""

from django import forms
from .models import ContactProfile


"""

name, email, și message: Acestea sunt câmpurile formularului și sunt definite ca obiecte de 
formular Django. Fiecare câmp are specificate caracteristici precum tipul de widget (în acest 
caz, utilizat pentru afișarea formularului în HTML), limita maximă de caractere, necesitatea 
completării și un atribut de atribute pentru a afișa un text de încărcare în câmpul formularului.

"""

class ContactForm(forms.ModelForm):


	name = forms.CharField(max_length=100, required=True,
		widget=forms.TextInput(attrs={
			'placeholder': '*Full name..',
			}))
	email = forms.EmailField(max_length=254, required=True, 
		widget=forms.TextInput(attrs={
			'placeholder': '*Email..',
			}))
	message = forms.CharField(max_length=1000, required=True, 
		widget=forms.Textarea(attrs={
			'placeholder': '*Message..',
			'rows': 6,
			}))




	class Meta:
		model = ContactProfile
		fields = ('name', 'email', 'message',)

"""

Meta: Aceasta este o clasă internă în formularul Django și este folosită pentru a specifica 
metadate despre formular, cum ar fi modelul cu care este legat (ContactProfile) și câmpurile 
din model care trebuie să apară în formular (fields). În acest caz, formularul va avea câmpuri 
pentru name, email și message, toate acestea provenind din modelul ContactProfile.

În ansamblu, acest formular (ContactForm) face mai ușoară crearea, validarea și gestionarea
datelor introduse de utilizatori atunci când aceștia transmit un mesaj de contact. Formularul poate 
fi apoi utilizat într-o vedere Django pentru a procesa datele introduse de utilizatori, de exemplu, pentru
a le salva în baza de date sau pentru a le utiliza în alte scopuri în aplicația ta.

"""

main/views.py
"""


Acest fragment de cod definește diverse vederi (views) în aplicația Django pentru gestionarea 
diferitelor pagini și funcționalități ale site-ului web. Iată o explicație detaliată a fiecărei
vederi și la ce se folosesc în program:

"""

from django.shortcuts import render
from django.contrib import messages
from .models import (
		UserProfile,
		Blog,
		Portfolio,
		Testimonial,
		Certificate
	)

from django.views import generic


from . forms import ContactForm

"""

IndexView:

Această vedere este asociată cu pagina principală a site-ului web.
Template-ul utilizat pentru această vedere este "main/index.html".
Funcția get_context_data este folosită pentru a obține datele de context necesare pentru 
template-ul paginii principale. Aici se includ testimoniale,certificate, bloguri și portofoliu 
care sunt afișate pe pagina principală.

"""

class IndexView(generic.TemplateView):
	template_name = "main/index.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		
		testimonials = Testimonial.objects.filter(is_active=True)
		certificates = Certificate.objects.filter(is_active=True)
		blogs = Blog.objects.filter(is_active=True)
		portfolio = Portfolio.objects.filter(is_active=True).order_by('-date')

		
		context["testimonials"] = testimonials
		context["certificates"] = certificates
		context["blogs"] = blogs
		context["portfolio"] = portfolio
		return context


"""

ContactView:

Această vedere este utilizată pentru pagina de contact a site-ului.
Template-ul utilizat este "main/contact.html".
Utilizează un formular definit în "forms.py" pentru a permite utilizatorilor să trimită mesaje de contact.
Dacă utilizatorul completează și trimite cu succes formularul, acesta este redirecționat către pagina 
principală, iar un mesaj de succes este afișat.

"""

class ContactView(generic.FormView):
	template_name = "main/contact.html"
	form_class = ContactForm
	success_url = "/"
	
	def form_valid(self, form):
		form.save()
		messages.success(self.request, 'Mulţumim, vă vom contacta in cel mai scurt timp!')
		return super().form_valid(form)

"""

PortfolioView:

Această vedere este folosită pentru a afișa o listă de proiecte din portofoliu.
Template-ul utilizat este "main/portfolio.html".
Utilizează modelul Portfolio pentru a obține proiectele de portofoliu care sunt marcate 
ca active și le afișează pe pagină.

"""

class PortfolioView(generic.ListView):
	model = Portfolio
	template_name = "main/portfolio.html"
	paginate_by = 10

	def get_queryset(self):
		return super().get_queryset().filter(is_active=True)

"""

PortfolioDetailView:

Această vedere afișează detaliile unui proiect specific din portofoliu.
Template-ul utilizat este "main/portfolio-detail.html".
Utilizează modelul Portfolio pentru a obține informații detaliate despre proiectul specific 
și le afișează pe pagină.

"""

class PortfolioDetailView(generic.DetailView):
	model = Portfolio
	template_name = "main/portfolio-detail.html"

"""

BlogView:

Această vedere este folosită pentru a afișa o listă de articole de blog.
Template-ul utilizat este "main/blog.html".
Utilizează modelul Blog pentru a obține articolele de blog care sunt marcate ca active și 
le afișează pe pagină.

"""

class BlogView(generic.ListView):
	model = Blog
	template_name = "main/blog.html"
	paginate_by = 10
	
	def get_queryset(self):
		return super().get_queryset().filter(is_active=True)


"""

BlogDetailView:

Această vedere afișează detaliile unui articol specific de blog.
Template-ul utilizat este "main/blog-detail.html".
Utilizează modelul Blog pentru a obține informații detaliate despre articolul 
specific și le afișează pe pagină.

"""

class BlogDetailView(generic.DetailView):
	model = Blog
	template_name = "main/blog-detail.html"


"""

Aceste vederi sunt esențiale pentru funcționarea și afișarea conținutului site-ului web. 
Ele procesează cererile primite de la utilizatori și afișează paginile corespunzătoare, 
în funcție de URL-urile accesate. De asemenea, utilizează modelele definite pentru a accesa
și afișa date din baza de date a aplicației Django.

"""

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{%endblock %}</title>
    <meta name="author" content="Did Coding Limited & James Granger Design">
    <link rel="canonical" href="{{request.path}}"/>
    <link rel="home" href="{% url 'main:home' %}"/>
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="keywords" content="{% block keywords %}{% endblock %}">

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/myicon.jpg' %}">
    <link rel="apple-touch-icon" type="images/myicon.jpg" href="{% static 'images/myicon.jpg' %}">

    <!-- ================================
    Start CSS
    ================================= -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% block extend_header%}{%endblock%}
    <!-- ================================
    End CSS
    ================================= -->

  </head>
  <body>
    {% include 'main/partials/messages.html' %}
    {% include 'main/partials/nav.html' %}

    {% block content %}
    {% endblock %}

    {% include 'main/partials/footer.html' %}

    <!-- ================================
    Start Scripts
    ================================= -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
    {% block extend_footer %}{%endblock%}
    <!-- ================================
    End Scripts
    ================================= -->
  </body>
</html>

main/templates/main/blog-detail.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">{{object.name|title}}</h1>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-auto">
          <div class="authorCol">
            <h4 class="smTitle pb-3">{{object.author|title}}</h4>
          </div>
        </div>
        <div class="col-md">
          <h4 class="smTitle pb-3">{{object.timestamp.date}}</h4>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="sectionSpaceSm">
    <div class="container">
      {{object.body|safe}}
    </div>
  </div>
</section>

{% endblock %}
<!-- ================================
End Content
================================= -->
   

main/templates/main/blog.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">Vizualizează postarile mele recente</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="lightBg">
    <div class="container">
      <div class="portfolioContentMain">
        <div class="row g-3 g-md-4 g-lg-5 portfolioRow">
          {% for obj in object_list %}
          <div class="col-md-6 pColMain">
            <div class="pCol">
              <a href="{% url 'main:blog' slug=obj.slug %}" >
              <img src="{{obj.image.url}}" alt="..." class="pImg">
              </a>
            </div>
          </div>
          {% endfor %}

        </div>
      </div>
    </div>
  </div>
</section>
<!-- ================================
End Content
================================= -->
{%endblock%} 
    

main/templates/main/contact.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">Contactaţi-mă</h1>
            <div class="bannerContent">
              <h1 class="xlTitle pb-md-3">czegobarna@yahoo.com</h1>
              <div class="bannerContent">
                <h1 class="xlTitle pb-md-3">+40770475106</h1>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="lightBg">
    <div class="container">
        <form id="contactForm" method="POST" action="/contact/">
        {% csrf_token %}
            <label for="name">Nume</label>
            {{form.name}}

            <label for="email">Email</label>
            {{form.email}}

            <label for="message">Mesaj</label>
            {{form.message}}

            <input class='btn btnPrimary' type="submit" value="Trimite">
        </form>
    </div>
  </div>
</section>
<!-- ================================
End Content
================================= -->
{%endblock%}
    

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="bannerSection">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-auto order-md-last">
          <div class="bannerUserImg">
            <img src="{{me.userprofile.avatar.url}}" alt="{{me.first_name|title}} {{me.last_name|title}} avatar">
          </div>
        </div>
        <div class="col-md">
          <div class="bannerContent">
            <h1 class="xlTitle pb-3">Bună, mă numesc {{me.last_name|title}}   {{me.first_name|title}}, un {{me.userprofile.title}} </br></h1>
            <p>{{me.userprofile.bio}}</p>
            <div class="bannerBtnCol">
              <div class="row">
                <div class="col-auto">
                  <a download href="{{me.userprofile.cv.url}}" class="btn btnPrimary">Descarcă cv-ul</a>
                </div>
                <div class="col-auto">
                  <a href=https://github.com/czegobarna class="btn btnOutline">Github
                    
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="sectionSpaceSm lightBg">
    <div class="container">
      <div class="row pb-3">
        <div class="col">
          <h4 class="smText regular">Certificate</h4>
        </div>

      </div>
      <div class="sliderOuter">
        <div class="swiper certificatesSlider">
          <div class="swiper-wrapper">
            {% for c in certificates %}
            {% if c.is_active %}
            <div class="swiper-slide">
              <div class="cardStyle1">
                <h4 class="mdTitle cs1Title">
                  <a href="javascript:void(0)">{{c.title}}</a>
                </h4>
                <ul class="cardOptionCol">
                  <li>{{c.date.date}}</li>
                  <li>{{c.name|title}}</li>
                </ul>
                <p>{{c.description}}</p>
              </div>
            </div>
            {% endif %}
            {% endfor %}
            
          </div>
        </div>            
        <div class="cert-swiper-button-next swiper-button-next swiperBtnStyle"></div>
        <div class="cert-swiper-button-prev swiper-button-prev swiperBtnStyle"></div>
        <div class="swiper-pagination swiperPaginationStyle posInitial"></div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="sectionSpace">
    <div class="container">
      <div class="portfolioCol">
        <div class="row pb-3">
          <div class="col">
            <h4 class="smText regular">Locuri de muncă</h4>
          </div>
          <div class="col-auto">
            <a href="{% url 'main:portfolios' %}" class="simpleLink">Vizionează toate</a>
          </div>
        </div>
        {% for p in portfolio %}
        {% if p.is_active %}
        <div class="portfolioCard">
          <div class="row g-4 align-items-center">
            <div class="col-md-auto">
              <div class="portfolioImgCol">
                <a href="{% url 'main:portfolio' slug=p.slug %}"><img src="{{p.image.url}}" alt="..."></a>
              </div>
            </div>
            <div class="col-md">
              <div class="portfolioContentCol">
                <h4 class="lgTitle"><a href="{% url 'main:portfolio' slug=p.slug %}">{{p.name}}</a></h4>
                <ul class="portfolioOption">
                  <li><span class="dateLbl">{{p.date.year}}</span></li>
                </ul>
                <p>{{p.description}}</p>
              </div>
            </div>
          </div>
        </div>
        {% endif %}
        {% endfor %}
        
      </div>
      <div class="testimonialCol">
        <h4 class="smText regular d-block">Momente</h4>
        <div class="testimonialSlider">
          <div class="swiper testimonialSwiper">
            <div class="swiper-wrapper">
              {% for t in testimonials %}
              {% if t.is_active %}
              <div class="swiper-slide">
                <div class="testimonialCard">
                  <div class="row align-items-center">
                    <div class="col-sm-auto">
                      <div class="tImgCol">
                        <img src="{{t.thumbnail.url}}" alt="...">
                      </div>
                    </div>
                    <div class="col-sm">
                      <div class="tContentCol">
                        <h4 class="xsTitle bold">{{t.name}} - {{t.role}}</h4>
                        <p>{{t.quote}}</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {% endif %}
              {% endfor %}

            </div>
            <div class="test-swiper-button-next swiper-button-next swiperBtnStyle"></div>
            <div class="test-swiper-button-prev swiper-button-prev swiperBtnStyle"></div>
          </div>


        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="sectionSpaceSm lightBg">
    <div class="container">
      <div class="row pb-3">
        <div class="col">
          <h4 class="smText regular">Postări recente</h4>
        </div>
        <div class="col-auto">
          <a href="{% url 'main:blogs' %}" class="simpleLink">View all</a>
        </div>
      </div>
      <div class="row g-3">
      {% for b in blogs %}
      {% if b.is_active %}
        <div class="col-lg-6">
          <div class="cardStyle1">
            <h4 class="mdTitle cs1Title"><a href="{% url 'main:blog' slug=b.slug %}">{{b.name}}</a></h4>
            <ul class="cardOptionCol">
              <li>{{b.timestamp.date}}</li>
              <li>{{b.author}}</li>
            </ul>
            <p>{{b.description}}</p>
          </div>
        </div>
        {% endif %}
        {% endfor %}

      </div>
    </div>
  </div>
</section>
{% endblock %}
<!-- ================================
End Content
================================= -->

main/templates/main/portfolio-detail.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">{{object.name}}</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="sectionSpaceSm">
    <div class="container">
      {{object.body|safe}}
    </div>
  </div>
</section>
<!-- ================================
End Content
================================= -->
{%endblock%}
    

main/templates/main/portfolio.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">Vizualizează locurile de muncă</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="lightBg">
    <div class="container">
      <div class="portfolioContentMain">
        <div class="row g-3 g-md-4 g-lg-5 portfolioRow">
          {% for obj in object_list %}
          <div class="col-md-6 pColMain">
            <div class="pCol">
              <a href="{% url 'main:portfolio' slug=obj.slug %}" >
              <img src="{{obj.image.url}}" alt="..." class="pImg">
              </a>
            </div>
          </div>
          {% endfor %}
          
        </div>
      </div>
    </div>
  </div>
</section>
<!-- ================================
End Content
================================= -->
{% endblock%}    